title: the Cross Orlando
url: "https://thecrossorlando.github.io"

jekyll_get:
  - data: posts
    json: 'https://kanishkkunal.stdlib.com/rss2json?url=https://medium.com/feed/@troylano'
  - data: posts
    json: 'https://kanishkkunal.stdlib.com/rss2json?url=https://tcandk.wordpress.com/feed/'
  - data: posts
    json: 'https://kanishkkunal.stdlib.com/rss2json?url=https://www.emsneighborhoodkitchen.com/feed.xml'
  - data: posts
    json: 'https://kanishkkunal.stdlib.com/rss2json?url=http://www.orlfoodlab.org/feed/'
  - data: posts
    json: 'https://kanishkkunal.stdlib.com/rss2json?url=http://polisinstitute.org/author/phil-hissom/feed/'

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
